/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package refactoring.crawler;

import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import refactoring.crawler.util.RefactoringCategory;

class RefactoringCrawlerTest {

  private static Dictionary<RefactoringCrawler.Settings, Double> settings;

  private static RefactoringCrawler refactoringCrawler;

  @BeforeAll
  static void setUp() {
    settings = new Hashtable<>();

    settings.put(RefactoringCrawler.Settings.T_CHANGE_METHOD_SIGNATURE, 1.0);
    settings.put(RefactoringCrawler.Settings.T_RENAME_METHOD, 1.0);
    settings.put(RefactoringCrawler.Settings.T_MOVE_METHOD, 1.0);
    settings.put(RefactoringCrawler.Settings.T_PUSH_DOWN_METHOD, 1.0);
    settings.put(RefactoringCrawler.Settings.T_PULL_UP_METHOD, 1.0);
    settings.put(RefactoringCrawler.Settings.T_RENAME_CLASS, 1.0);

    refactoringCrawler = new RefactoringCrawler("TEST_PROJECT_NAME", settings);
  }

  @Test
  void testRenameMethod() {
    String source =
        "/*\n"
            + " * This Java source file was generated by the Gradle 'init' task.\n"
            + " */\n"
            + "package refactoring.crawler;\n"
            + "\n"
            + "public class Library {\n"
            + "\tprivate int a;\n"
            + "\tprivate int b;\n"
            + "\n"
            + "\tpublic void foo() {\n"
            + "\t\tSystem.out.println(11111);\n"
            + "\t}\n"
            + "\n"
            + "\tpublic void bar() {\n"
            + "\t\tthis.foo();\n"
            + "\t}\n"
            + "}\n";

    String newVersion =
        "/*\n"
            + " * This Java source file was generated by the Gradle 'init' task.\n"
            + " */\n"
            + "package refactoring.crawler;\n"
            + "\n"
            + "public class Library {\n"
            + "\tprivate int a;\n"
            + "\tprivate int b;\n"
            + "\n"
            + "\tpublic void foo12() {\n"
            + "\t\tSystem.out.println(11111);\n"
            + "\t}\n"
            + "\n"
            + "\tpublic void bar() {\n"
            + "\t\tthis.foo12();\n"
            + "\t}\n"
            + "}\n";

    refactoringCrawler.detect(source, newVersion);
    List<RefactoringCategory> categories = refactoringCrawler.getRefactoringCategories();
    System.out.println(categories);
  }
}
