/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package refactoring.crawler;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.Dictionary;
import java.util.HashMap;
import java.util.Hashtable;

import static org.junit.jupiter.api.Assertions.*;

class RefactoringCrawlerTest {

	private static Dictionary<RefactoringCrawler.Settings, Double> settings;

	private static RefactoringCrawler refactoringCrawler;

	@BeforeAll
	static void setUp() {
		settings = new Hashtable<>();

		settings.put(RefactoringCrawler.Settings.T_CHANGE_METHOD_SIGNATURE, 0.5);
		settings.put(RefactoringCrawler.Settings.T_RENAME_METHOD, 0.5);
		settings.put(RefactoringCrawler.Settings.T_MOVE_METHOD, 0.5);
		settings.put(RefactoringCrawler.Settings.T_PUSH_DOWN_METHOD, 0.6);
		settings.put(RefactoringCrawler.Settings.T_PULL_UP_METHOD, 0.6);

		refactoringCrawler = new RefactoringCrawler("TEST_PROJECT_NAME", settings);
	}


	@Test
	void testSomeLibraryMethod() {
	}
}
